name: Build and publish core querent packages

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # ex. v1.0.0
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+" # ex. v1.1.0-rc1
      - "v0.0.1" # used for testing only
      - "v0.0.1-rc[0-9]+" # used for testing only
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version (v#.#.#[-rc#])"
        required: true
env:
  INPUT_RELEASE_VERSION: ${{ github.event.inputs.release-version || github.ref_name }}
  POSTGRESQL_VERSION: 16.4.0
jobs:
  build-windows-binaries:
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]
    name: Build ${{ matrix.target }}
    runs-on: windows-2022
    steps:
      - name: Vcpkg install
        shell: powershell
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows         
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Build
        run: cargo build --features bundled
